
indent_style = "Block"
use_small_heuristics = "Off" # "Default"
binop_separator = "Front"
# combine_control_expr = true
comment_width = 120 # 80
condense_wildcard_suffixes = true # false
control_brace_style = "AlwaysSameLine"
# disable_all_formatting = false
error_on_line_overflow = false # true
# error_on_unformatted = false
fn_args_density = "Tall"
brace_style = "PreferSameLine" # "SameLineWhere"
empty_item_single_line = true
fn_single_line = false
# where_single_line = false
force_explicit_abi = true
format_strings = false
format_macro_matchers = false
format_macro_bodies = true
hard_tabs = false
imports_indent = "Block" # "Visual"
imports_layout = "Mixed"
merge_imports = false
match_block_trailing_comma = false
max_width = 120 # 100
merge_derives = true
# force_multiline_blocks = false
newline_style = "Unix"
normalize_comments = false
remove_nested_parens = true
reorder_imports = true
reorder_modules = true